version: '1.0'
name: pipeline-20220721
displayName: push
triggers:
  trigger: auto
  push:
    branches:
      prefix:
        - ''
stages:
  - name: stage-06098125
    displayName: 未命名
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: build@golang
        name: build_golang
        displayName: Golang 构建
        golangVersion: '1.16'
        commands:
          - mkdir output
          - GO111MODULE="on" GOPROXY="https://goproxy.cn,direct" go mod tidy
          - GOOS=linux GOARCH=amd64 go build -o output/main.amd64 ./app/main.go
          - GOOS=linux GOARCH=386 go build -o output/main.linux32 ./app/main.go
          - GOOS=windows GOARCH=amd64 go build -o output/main.win64.exe ./app/main.go
          - GOOS=windows GOARCH=386 go build -o output/main.win32.exe ./app/main.go
          - GOOS=darwin GOARCH=amd64 go build -o output/main.darwin ./app/main.go
          - chmod +X output/main.linux32
          - ./output/main.linux32
        caches:
          - /go/pkg/mod
        notify: []
        strategy:
          retry: '0'
          expression: []
strategy:
  blocking: true
permissions:
  - role: admin
    members:
      - aurora-engines
