version: '1.0'
name: pipeline-20220721
displayName: push
triggers:
  trigger: auto
  push:
    branches:
      prefix:
        - ''
stages:
  - name: stage-06098125
    displayName: 未命名
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: build@golang
        name: build_golang
        displayName: Golang 构建
        golangVersion: '1.16'
        commands:
          - cd app
          - mkdir output
          - go env -w  GOPROXY="https://goproxy.cn,direct"
          - go build -o output/main main.go
          - chmod +X output/main
          - ./output/main
        caches:
          - /go/pkg/mod
        notify: []
        strategy:
          retry: '0'
          expression: []
strategy:
  blocking: true
permissions:
  - role: admin
    members:
      - aurora-engines
